# Generated by Django 4.2.7 on 2023-11-06 18:45

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarPark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Парк автомобилей',
                'verbose_name_plural': 'Парки автомобилей',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Клиент')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etaxi.city')),
            ],
            options={
                'verbose_name': 'Водитель',
                'verbose_name_plural': 'Водители',
            },
        ),
        migrations.CreateModel(
            name='DriverMany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverThrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etaxi.driver')),
            ],
        ),
        migrations.CreateModel(
            name='TaxiCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('carType', models.CharField(choices=[('SD', 'Седан'), ('HT', 'Хэтчбэк'), ('LF', 'Лифтбэк'), ('JP', 'Джип'), ('UN', 'Универсал'), ('MW', 'Минивэн'), ('PK', 'Пикап')], max_length=2, verbose_name='Тип Кузова')),
                ('regNumber', models.CharField(max_length=10, verbose_name='Рег. номер')),
                ('yearIssu', models.IntegerField(verbose_name='Год выпуска')),
                ('status', models.BooleanField(default=False)),
                ('discription', models.TextField()),
                ('image', models.ImageField(upload_to='images/cars/%Y-%m-%d/')),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ManyToManyField(through='etaxi.DriverMany', to='etaxi.driver')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
            },
        ),
        migrations.CreateModel(
            name='TaxiCarMany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carParkThrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etaxi.carpark')),
                ('taxiCarThrough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etaxi.taxicar')),
            ],
        ),
        migrations.CreateModel(
            name='ParkManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=40, verbose_name='Имя')),
                ('lastName', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etaxi.city', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Менеджер парка',
                'verbose_name_plural': 'Менеджеры парков',
            },
        ),
        migrations.AddField(
            model_name='drivermany',
            name='taxiCarThrough',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etaxi.taxicar'),
        ),
        migrations.AddField(
            model_name='carpark',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etaxi.city'),
        ),
        migrations.AddField(
            model_name='carpark',
            name='parkManager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etaxi.parkmanager'),
        ),
        migrations.AddField(
            model_name='carpark',
            name='taxiCar',
            field=models.ManyToManyField(through='etaxi.TaxiCarMany', to='etaxi.taxicar'),
        ),
    ]
