# Generated by Django 4.2.7 on 2023-11-06 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etaxi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxicar',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='etaxi.city', verbose_name='Город'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Водитель'),
        ),
        migrations.AlterField(
            model_name='taxicar',
            name='discription',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='taxicar',
            name='image',
            field=models.ImageField(upload_to='images/cars/%Y-%m-%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='taxicar',
            name='regNumber',
            field=models.CharField(max_length=20, verbose_name='Рег. номер'),
        ),
        migrations.AlterField(
            model_name='taxicar',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус(занят/свободен)'),
        ),
    ]
