# Generated by Django 4.2.7 on 2023-11-06 20:44

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('etaxi', '0002_taxicar_city_alter_driver_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carpark',
            options={'verbose_name': 'Таксопарк автомобилей', 'verbose_name_plural': 'Таксопарки автомобилей'},
        ),
        migrations.AlterModelOptions(
            name='parkmanager',
            options={'verbose_name': 'Менеджер таксопарка', 'verbose_name_plural': 'Менеджеры таксопарков'},
        ),
        migrations.AddField(
            model_name='carpark',
            name='name',
            field=models.CharField(default=None, max_length=50, verbose_name='название таксопарка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carpark',
            name='address',
            field=models.TextField(verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='carpark',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etaxi.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='carpark',
            name='parkManager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etaxi.parkmanager', verbose_name='Менеджер'),
        ),
        migrations.AlterField(
            model_name='carpark',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='carpark',
            name='taxiCar',
            field=models.ManyToManyField(through='etaxi.TaxiCarMany', to='etaxi.taxicar', verbose_name='Автомобили'),
        ),
        migrations.AlterField(
            model_name='taxicarmany',
            name='taxiCarThrough',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etaxi.taxicar', verbose_name='автомобили таксопарка'),
        ),
    ]
