# Generated by Django 4.2.7 on 2023-11-06 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('etaxi', '0003_carpark_drivermany_taxicar_taxicarmany_parkmanager_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpark',
            name='dateCreation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
