# Generated by Django 4.2.7 on 2023-11-08 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etaxi', '0006_alter_carpark_parkmanager_alter_parkmanager_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityPark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.AlterField(
            model_name='carpark',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etaxi.citypark', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etaxi.citypark'),
        ),
        migrations.AlterField(
            model_name='feedbackvideo',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etaxi.citypark', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='parkmanager',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etaxi.citypark', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='taxicar',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='etaxi.citypark', verbose_name='Город'),
        ),
    ]
