# Generated by Django 4.2.7 on 2023-11-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etaxi', '0007_citypark_alter_carpark_city_alter_driver_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citypark',
            options={'ordering': ['name'], 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
        migrations.AddField(
            model_name='carpark',
            name='dateUpdate',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения'),
        ),
        migrations.AddField(
            model_name='feedbackvideo',
            name='dateUpdate',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения'),
        ),
        migrations.AddField(
            model_name='parkmanager',
            name='dateUpdate',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения'),
        ),
        migrations.AddField(
            model_name='taxicar',
            name='dateUpdate',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='taxicar',
            name='dateCreation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='taxicar',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Занят/Свободен'),
        ),
    ]
