# Generated by Django 4.2.7 on 2023-11-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etaxi', '0008_alter_citypark_options_carpark_dateupdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkmanager',
            name='image',
            field=models.ImageField(null=True, upload_to='images/managers/%Y-%m-%d/', verbose_name='Фото'),
        ),
    ]
