# Generated by Django 4.2.7 on 2023-11-20 15:51

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('etaxi', '0009_parkmanager_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='confirmation',
            field=models.BooleanField(default=False, verbose_name='Соглашение на обработку'),
        ),
        migrations.AddField(
            model_name='driver',
            name='question',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Вопрос клиента'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etaxi.citypark', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='feedbackvideo',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='video/feedback/%Y-%m-%d/', verbose_name='Видеофайл'),
        ),
        migrations.AlterField(
            model_name='parkmanager',
            name='dateCreation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='parkmanager',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/managers/%Y-%m-%d/', verbose_name='Загрузить Фото'),
        ),
        migrations.AlterField(
            model_name='taxicar',
            name='image',
            field=models.ImageField(upload_to='images/cars/%Y-%m-%d/', verbose_name='Загрузить Фото'),
        ),
    ]
