# Generated by Django 4.2.7 on 2023-11-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etaxi', '0010_driver_confirmation_driver_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='confirmation',
            field=models.BooleanField(verbose_name='Соглашение на обработку получено'),
        ),
    ]
