# Generated by Django 4.2.7 on 2023-11-21 13:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('etaxi', '0011_alter_driver_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='etaxi.citypark', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='confirmation',
            field=models.BooleanField(default=True, verbose_name='Соглашение на обработку получено'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='name',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^[a-zA-Zа-яА-Я ]+$', message='Введите только имя без цифр и символов !;№@')], verbose_name='Водитель'),
        ),
    ]
