# Generated by Django 4.2.7 on 2023-11-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etaxi', '0013_alter_driver_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='question',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Вопрос клиента'),
        ),
    ]
