# Generated by Django 4.2.7 on 2023-11-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etaxi', '0015_citypark_latitude_citypark_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citypark',
            name='latitude',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='citypark',
            name='longitude',
            field=models.FloatField(verbose_name='Долгота'),
        ),
    ]
