# Generated by Django 4.2.7 on 2023-11-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etaxi', '0016_alter_citypark_latitude_alter_citypark_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxicar',
            name='engineCapacity',
            field=models.FloatField(default=1.5, max_length=100, verbose_name='Марка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taxicar',
            name='gearType',
            field=models.CharField(choices=[('AT', 'АКПП'), ('MC', 'МКПП')], default='АКПП', max_length=2, verbose_name='Коробка передач'),
            preserve_default=False,
        ),
    ]
