# Generated by Django 4.2.7 on 2023-11-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etaxi', '0018_alter_taxicar_enginecapacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxicar',
            name='carType',
            field=models.CharField(blank=True, choices=[('SD', 'Седан'), ('HT', 'Хэтчбэк'), ('LF', 'Лифтбэк'), ('JP', 'Джип'), ('UN', 'Универсал'), ('MW', 'Минивэн'), ('PK', 'Пикап')], max_length=2, null=True, verbose_name='Тип Кузова'),
        ),
        migrations.AlterField(
            model_name='taxicar',
            name='discription',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='taxicar',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='taxicar',
            name='regNumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Рег. номер'),
        ),
    ]
