# Generated by Django 4.2.7 on 2023-11-26 19:10

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('etaxi', '0021_parkmanager_thirdname_alter_parkmanager_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(error_messages={'required': 'Please enter your name'}, max_length=128, region=None, unique=True, verbose_name='Телефон'),
        ),
    ]
