# Generated by Django 4.2.7 on 2023-11-26 19:52

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('etaxi', '0023_alter_driver_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAbout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название видео')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/videoabout/%Y-%m-%d/', verbose_name='Видеофайл')),
                ('youtube', embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='Youtube ссылка')),
                ('dateCreation', models.DateTimeField(auto_now_add=True)),
                ('dateUpdate', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Видео о нас',
                'verbose_name_plural': 'Виде о нас',
            },
        ),
    ]
